# Form implementation generated from reading ui file 'src/ui/ciphera.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
QtCore.QDir.addSearchPath('assets', 'assets/')
from src.controller.cipheraController import CipheraController

class Ui_CipheraWindow(object):

    def setupUi(self, CipheraWindow):
        CipheraWindow.setObjectName("CipheraWindow")
        CipheraWindow.resize(800, 592)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        CipheraWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets:icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        CipheraWindow.setWindowIcon(icon)
        CipheraWindow.setAutoFillBackground(False)
        CipheraWindow.setStyleSheet("#CipheraWindow{\n"
"    background-color: rgb(241, 241, 241);\n"
"}\n"
"#FrameWidget{\n"
"    background-color: rgb(241, 241, 241);\n"
"}")
        self.FrameWidget = QtWidgets.QWidget(parent=CipheraWindow)
        self.FrameWidget.setAutoFillBackground(False)
        self.FrameWidget.setObjectName("FrameWidget")
        self.CipheraLabel = QtWidgets.QLabel(parent=self.FrameWidget)
        self.CipheraLabel.setGeometry(QtCore.QRect(330, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(24)
        self.CipheraLabel.setFont(font)
        self.CipheraLabel.setStyleSheet("QLabel {\n"
"color:rgb(94, 20, 250)\n"
"}")
        self.CipheraLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CipheraLabel.setObjectName("CipheraLabel")

        self.IconLogo = QtWidgets.QLabel(parent=self.FrameWidget)
        self.IconLogo.setGeometry(QtCore.QRect(310, 20, 40, 40))
        self.IconLogo.setAutoFillBackground(False)
        self.IconLogo.setText("")
        self.IconLogo.setPixmap(QtGui.QPixmap("assets:icon.png"))
        self.IconLogo.setScaledContents(True)

        self.LeftFrame = QtWidgets.QFrame(parent=self.FrameWidget)
        self.LeftFrame.setGeometry(QtCore.QRect(40, 80, 340, 480))
        self.LeftFrame.setStyleSheet("#LeftFrame{\n"
"    border-radius:10px;\n"
"    border: 2px solid;\n"
"    border-top-color:  rgb(94, 20, 250);\n"
"    border-right-color:  rgb(20, 94, 250);\n"
"    border-bottom-color:  rgb(20, 94, 250);\n"
"    border-left-color:  rgb(94, 20, 250);\n"
"}")
        self.LeftFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.LeftFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.LeftFrame.setObjectName("LeftFrame")
        self.CipherButton = QtWidgets.QPushButton(parent=self.LeftFrame)
        self.CipherButton.setGeometry(QtCore.QRect(40, 360, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CipherButton.setFont(font)
        self.CipherButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CipherButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.CipherButton.setStyleSheet("#CipherButton:pressed{\n"
"    background-color: rgb(85, 139, 252);\n"
"}\n"
"#CipherButton{\n"
"background-color: rgb(20, 94, 250);\n"
"border:none;\n"
"border-radius:10px;\n"
"color:rgb(240,240,240);\n"
"padding-left:25px;\n"
"}\n"
"")
        self.CipherButton.setIconSize(QtCore.QSize(20, 20))
        self.CipherButton.setObjectName("CipherButton")
        self.label = QtWidgets.QLabel(parent=self.LeftFrame)
        self.label.setGeometry(QtCore.QRect(60, 370, 24, 24))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets:lock.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.DecipherButton = QtWidgets.QPushButton(parent=self.LeftFrame)
        self.DecipherButton.setGeometry(QtCore.QRect(180, 360, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DecipherButton.setFont(font)
        self.DecipherButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.DecipherButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.DecipherButton.setStyleSheet("#DecipherButton:pressed{\n"
"    background-color: rgb(131, 79, 241);\n"
"}\n"
"#DecipherButton{\n"
"background-color: rgb(94, 20, 250);\n"
"border:none;\n"
"border-radius:10px;\n"
"color:rgb(240,240,240);\n"
"padding-left:25px;\n"
"}\n"
"")
        self.DecipherButton.setIconSize(QtCore.QSize(20, 20))
        self.DecipherButton.setObjectName("DecipherButton")
        self.label_2 = QtWidgets.QLabel(parent=self.LeftFrame)
        self.label_2.setGeometry(QtCore.QRect(190, 370, 24, 24))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets:lockopen.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.PasswordLabel = QtWidgets.QLabel(parent=self.LeftFrame)
        self.PasswordLabel.setGeometry(QtCore.QRect(90, 30, 160, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setStyleSheet("color: rgb(20, 94, 250);")
        self.PasswordLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.PasswordInput = QtWidgets.QLineEdit(parent=self.LeftFrame)
        self.PasswordInput.setGeometry(QtCore.QRect(70, 60, 200, 30))
        self.PasswordInput.setStyleSheet("border-radius:5px;\n"
"border:2px solid;\n"
"border-color: rgb(94, 20, 250);\n"
"background-color: rgb(255, 255, 255);")
        self.PasswordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.PasswordInput.setObjectName("PasswordInput")
        self.SecurityLabel = QtWidgets.QLabel(parent=self.LeftFrame)
        self.SecurityLabel.setGeometry(QtCore.QRect(70, 160, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SecurityLabel.setFont(font)
        self.SecurityLabel.setStyleSheet("color: rgb(20, 94, 250);")
        self.SecurityLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SecurityLabel.setObjectName("SecurityLabel")
        self.AlgorithmSelect = QtWidgets.QComboBox(parent=self.LeftFrame)
        self.AlgorithmSelect.setGeometry(QtCore.QRect(180, 110, 91, 31))
        self.AlgorithmSelect.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.AlgorithmSelect.setStyleSheet("""
            QComboBox {
                margin-right: 3px;
                background-color: rgb(222, 221, 218);
                padding-left: 5px;
                color: rgb(20, 94, 250);
            }
            QComboBox QAbstractItemView {
                background-color: rgb(222, 221, 218);
                selection-background-color: rgb(255, 0, 0);
                selection-color: white;
            }
            QComboBox::item {
                color: rgb(94, 20, 250);
                background-color: rgb(222, 221, 218);
            }
            QComboBox::item:hover {
                color: white;
                background-color: rgb(255, 0, 0);
            }
        """)
        self.AlgorithmSelect.setObjectName("AlgorithmSelect")
        self.AlgorithmLabel = QtWidgets.QLabel(parent=self.LeftFrame)
        self.AlgorithmLabel.setGeometry(QtCore.QRect(70, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AlgorithmLabel.setFont(font)
        self.AlgorithmLabel.setStyleSheet("color: rgb(94, 20, 250);")
        self.AlgorithmLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AlgorithmLabel.setObjectName("AlgorithmLabel")
        self.HighButton = QtWidgets.QPushButton(parent=self.LeftFrame)
        self.HighButton.setGeometry(QtCore.QRect(80, 190, 41, 41))
        self.HighButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.HighButton.setStyleSheet("background-color: rgb(51, 209, 122);\n"
"border:none;\n"
"border-radius:10px;")
        self.HighButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets:lock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HighButton.setIcon(icon1)
        self.HighButton.setIconSize(QtCore.QSize(24, 24))
        self.HighButton.setObjectName("HighButton")
        self.MediumButton = QtWidgets.QPushButton(parent=self.LeftFrame)
        self.MediumButton.setGeometry(QtCore.QRect(150, 190, 41, 41))
        self.MediumButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MediumButton.setStyleSheet(";\n"
"background-color: rgb(245, 194, 17);\n"
"border:none;\n"
"border-radius:10px;")
        self.MediumButton.setText("")
        self.MediumButton.setIcon(icon1)
        self.MediumButton.setIconSize(QtCore.QSize(24, 24))
        self.MediumButton.setObjectName("MediumButton")
        self.LowButton = QtWidgets.QPushButton(parent=self.LeftFrame)
        self.LowButton.setGeometry(QtCore.QRect(220, 190, 41, 41))
        self.LowButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.LowButton.setStyleSheet("border:none;\n"
"background-color: rgb(224, 27, 36);\n"
"border-radius:10px;")
        self.LowButton.setText("")
        self.LowButton.setIcon(icon1)
        self.LowButton.setIconSize(QtCore.QSize(24, 24))
        self.LowButton.setObjectName("LowButton")
        self.ResumeLabel = QtWidgets.QLabel(parent=self.LeftFrame)
        self.ResumeLabel.setGeometry(QtCore.QRect(120, 290, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResumeLabel.setFont(font)
        self.ResumeLabel.setStyleSheet("color: rgb(94, 20, 250);")
        self.ResumeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ResumeLabel.setObjectName("ResumeLabel")
        self.AlgorithmResumeLabel = QtWidgets.QLabel(parent=self.LeftFrame)
        self.AlgorithmResumeLabel.setGeometry(QtCore.QRect(70, 320, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AlgorithmResumeLabel.setFont(font)
        self.AlgorithmResumeLabel.setStyleSheet("color: rgb(20, 94, 250);")
        self.AlgorithmResumeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AlgorithmResumeLabel.setObjectName("AlgorithmResumeLabel")
        self.SecurityResumeLabel = QtWidgets.QLabel(parent=self.LeftFrame)
        self.SecurityResumeLabel.setGeometry(QtCore.QRect(180, 320, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SecurityResumeLabel.setFont(font)
        self.SecurityResumeLabel.setStyleSheet("color: rgb(20, 94, 250);")
        self.SecurityResumeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SecurityResumeLabel.setObjectName("SecurityResumeLabel")
        self.InformationLabel = QtWidgets.QLabel(parent=self.LeftFrame)
        self.InformationLabel.setGeometry(QtCore.QRect(70, 240, 200, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.InformationLabel.setFont(font)
        self.InformationLabel.setStyleSheet("")
        self.InformationLabel.setMidLineWidth(0)
        self.InformationLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.InformationLabel.setWordWrap(True)
        self.InformationLabel.setObjectName("InformationLabel")
        self.LoadResultButton = QtWidgets.QPushButton(parent=self.LeftFrame)
        self.LoadResultButton.setGeometry(QtCore.QRect(110, 420, 120, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LoadResultButton.setFont(font)
        self.LoadResultButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.LoadResultButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.LoadResultButton.hide()
        self.LoadResultButton.setStyleSheet("#LoadResultButton:pressed{\n"
"    \n"
"    background-color: rgb(123, 187, 209);\n"
"}\n"
"#LoadResultButton{\n"
"    background-color: rgb(0, 135, 182);\n"
"border:none;\n"
"border-radius:10px;\n"
"color:rgb(240,240,240);\n"
"}\n"
"")
        self.LoadResultButton.setIconSize(QtCore.QSize(20, 20))
        self.LoadResultButton.setObjectName("LoadResultButton")
        self.RightFrame = QtWidgets.QFrame(parent=self.FrameWidget)
        self.RightFrame.setGeometry(QtCore.QRect(420, 80, 340, 480))
        self.RightFrame.setStyleSheet("#RightFrame{\n"
"    border-radius:10px;\n"
"    border: 2px solid;\n"
"    border-top-color:  rgb(94, 20, 250);\n"
"    border-right-color:  rgb(20, 94, 250);\n"
"    border-bottom-color:  rgb(20, 94, 250);\n"
"    border-left-color:  rgb(94, 20, 250);\n"
"}")
        self.RightFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RightFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RightFrame.setObjectName("RightFrame")
        self.LoadFileButton = QtWidgets.QPushButton(parent=self.RightFrame)
        self.LoadFileButton.setGeometry(QtCore.QRect(70, 20, 200, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LoadFileButton.setFont(font)
        self.LoadFileButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.LoadFileButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.LoadFileButton.setStyleSheet("#LoadFileButton:pressed{\n"
"    background-color: rgb(131, 79, 241);\n"
"}\n"
"#LoadFileButton{\n"
"    background-color: rgb(68, 60, 199);\n"
"border:none;\n"
"border-radius:10px;\n"
"color:rgb(240,240,240);\n"
"}\n"
"")
        self.LoadFileButton.setIconSize(QtCore.QSize(20, 20))
        self.LoadFileButton.setObjectName("LoadFileButton")
        self.label_3 = QtWidgets.QLabel(parent=self.RightFrame)
        self.label_3.setGeometry(QtCore.QRect(109, 30, 21, 21))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("padding-top:2px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("assets:upload.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(parent=self.RightFrame)
        self.textEdit.setGeometry(QtCore.QRect(30, 109, 280, 341))
        self.textEdit.setStyleSheet("border-radius:7px;\n"
"border:2px solid;\n"
"border-color: rgb(0, 135, 182);\n"
"background-color: rgb(222, 221, 218);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setReadOnly(True)
        self.MessageFile = QtWidgets.QLabel(parent=self.RightFrame)
        self.MessageFile.setGeometry(QtCore.QRect(70, 80, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MessageFile.setFont(font)
        self.MessageFile.setStyleSheet("color: rgb(20, 94, 250); font-size:14px;")
        self.MessageFile.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MessageFile.setObjectName("MessageFile")

        CipheraWindow.setCentralWidget(self.FrameWidget)
        self.statusbar = QtWidgets.QStatusBar(parent=CipheraWindow)
        self.statusbar.setObjectName("statusbar")
        CipheraWindow.setStatusBar(self.statusbar)
        self.retranslateUi(CipheraWindow)
        QtCore.QMetaObject.connectSlotsByName(CipheraWindow)

    def retranslateUi(self, CipheraWindow):
        _translate = QtCore.QCoreApplication.translate
        CipheraWindow.setWindowTitle(_translate("CipheraWindow", "Ciphera"))
        self.CipheraLabel.setText(_translate("CipheraWindow", "Ciphera"))
        self.CipherButton.setText(_translate("CipheraWindow", "Cipher"))
        self.DecipherButton.setText(_translate("CipheraWindow", "Decipher"))
        self.PasswordLabel.setText(_translate("CipheraWindow", "Enter the Password"))
        self.SecurityLabel.setText(_translate("CipheraWindow", "Select a Level of Security"))
        self.AlgorithmLabel.setText(_translate("CipheraWindow", "Algorithm"))
        self.ResumeLabel.setText(_translate("CipheraWindow", "Resume"))
        self.AlgorithmResumeLabel.setText(_translate("CipheraWindow", "SHA256"))
        self.SecurityResumeLabel.setText(_translate("CipheraWindow", "MEDIUM"))
        self.InformationLabel.setText(_translate("CipheraWindow", "Security is associated with the number of iterations of a process that strengthens encryption."))
        self.LoadResultButton.setText(_translate("CipheraWindow", "Load Result"))
        self.LoadFileButton.setText(_translate("CipheraWindow", "Load File"))
        self.MessageFile.setText(_translate("CipheraWindow", "File"))

class CipheraWindow(QtWidgets.QMainWindow, Ui_CipheraWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.main_controller = CipheraController(self)
        self.LoadFileButton.clicked.connect(self.main_controller.load_file)

